[winnings]
[[winnings.odds]]
symbol = 1
3 = 10
4 = 20
5 = 30
[[winnings.odds]]
symbol = 2
3 = 1
4 = 1
5 = 1
[[winnings.odds]]
symbol = 3
3 = 1
4 = 2
5 = 3
[winnings.default]
min = 3
max = 5
[[winnings.winning_rule]]
coords = [[0, 0], [0, 1], [0, 2], [0, 3], [0, 4]]
[game]
wild_id = 1
jackpot_id = 8
rows = 3
cols = 5
mode = 'LIGATURE'
[[round]]
build_nums = 1
[[spark]]   # 触发免费游戏配置
mode = 'COUNT_SYMBOL' # 匹配模式
symbol = 1 # 触发图标元素
min = 3 # 触发最小数量
max = 5 # 触发最大数量
[spark.freespin] # 触发freespin配置
mode = 'LIGATURE' # 触发游戏模式
build_nums = 10 # 执行次数
[prob]
[[prob.symbol]]
1 = 0.1
2 = 0.1
3 = 0.1
4 = 0.1