[winnings]
[[winnings.odds]]
symbol = 1
3 = 10
4 = 20
5 = 30
[[winnings.odds]]
symbol = 2
3 = 1
4 = 1
5 = 1
[[winnings.odds]]
symbol = 3
3 = 1
4 = 2
5 = 3
[winnings.default]
min = 3
max = 5
[[winnings.winning_rule]]
coords = [[0, 0], [0, 1], [0, 2], [0, 3], [0, 4]]
[game]
wild_id = 1
jackpot_id = 8
rows = 3
cols = 5
mode = 'LIGATURE'
[[round]]
build_nums = 1
[[round]]
[prob]
[[prob.symbol]]
1 = 0.1
2 = 0.1
3 = 0.1
4 = 0.1